services:
  - type: web
    name: ai-pm-hub-web
    env: node
    plan: free
    buildCommand: cd apps/web && npm install && npm run build
    startCommand: cd apps/web && npm start
    envVars:
      - key: NODE_ENV
        value: production
