services:
  - type: web
    name: ai-pm-hub-web
    env: node
    plan: free
    rootDir: apps/web
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
