services:
  - type: web
    name: ai-pm-hub-web
    env: node
    plan: free
    buildCommand: "npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
